### ISSUE TITLE
Failed to create LSP

### ISSUE THREAD

**Issue by artemd93** [CiscoDevNet/Opendaylight-BGP-Pathman-apps#2]
Hi there,

I have a little test case:

1. Click "Create new LSP" on pathman app
2. Select source and destination
3. Click "Go"
4. Choose path
5. Enter name "mypath"
6. Click "Deploy"

It's expected LSP to be created, but in log I can see message as follows:

9900 2017-01-03 14:45:31.791 UTC root:rest_interface_parser INFO: Commands Recieved: {u'path': [u'router1', u'router2'], u'name': u'mypat\x00', u'option': u'create'}

As you can see, the last symbol has been replaced with "\x00" combination, witch causes an ODL error:

[Fatal Error] :3:16: An invalid XML character (Unicode: 0x0) was found in the element content of the document.

Any ideas?

**Comment by nikmon2** [comment]
I have seen this when using Firefox, so:
1. Are you using Firefox?
2. Can You try the same using Chrome?

Cheers,
Niklas

**Comment by artemd93** [comment]
Yes, that was FF. Works fine with Chrome, thanks.
